enum PurposeErrorCodes {
  INVALID_FORMAL_CHECK = "INVALID_FORMAL_CHECK",
  INVALID_STATUS_CODE = "INVALID_STATUS_CODE",
  INVALID_PURPOSE = "INVALID_PURPOSE",
  INVALID_DATE = "INVALID_DATE",
  ESERVICE_NOT_ASSOCIATED = "ESERVICE_NOT_ASSOCIATED",
  ESERVICE_NOT_FOUND = "ESERVICE_NOT_FOUND",
  PURPOSE_NOT_FOUND = "PURPOSE_NOT_FOUND",
  CONSUMER_NOT_FOUND = "CONSUMER_NOT_FOUND",
  PRODUCER_NOT_FOUND = "PRODUCER_NOT_FOUND",
  PURPOSE_AND_STATUS_NOT_UNIQUE = "PURPOSE_AND_STATUS_NOT_UNIQUE",
}

export default PurposeErrorCodes;
