export enum PurposeErrorCodes {
  INVALID_ROW_SCHEMA = "INVALID_ROW_SCHEMA",
  INVALID_STATUS_CODE = "INVALID_STATUS_CODE",
  INVALID_PURPOSE = "INVALID_PURPOSE",
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_DATE = "INVALID_DATE",
  TENANT_IS_NOT_PRODUCER_OR_CONSUMER = "TENANT_IS_NOT_PRODUCER_OR_CONSUMER",
  PURPOSE_NOT_FOUND = "PURPOSE_NOT_FOUND",
  INVALID_REQUEST_COUNT = "INVALID_REQUEST_COUNT",
  INVALID_CSV = "INVALID_CSV",
  INVALID_CSV_HEADERS = "INVALID_CSV_HEADERS",
  INVALID_DELIMITER = "INVALID_DELIMITER",
  PURPOSE_AND_STATUS_AND_TOKEN_NOT_UNIQUE = "PURPOSE_AND_STATUS_AND_TOKEN_NOT_UNIQUE",
}
