export enum PurposeErrorCodes {
  INVALID_ROW_SCHEMA = "INVALID_ROW_SCHEMA",
  INVALID_STATUS_CODE = "INVALID_STATUS_CODE",
  INVALID_PURPOSE = "INVALID_PURPOSE",
  INVALID_DATE = "INVALID_DATE",
  TENANT_IS_NOT_PRODUCER_OR_CONSUMER = "TENANT_IS_NOT_PRODUCER_OR_CONSUMER",
  PURPOSE_NOT_FOUND = "PURPOSE_NOT_FOUND",
  PRODUCER_NOT_FOUND = "PRODUCER_NOT_FOUND",
  INVALID_REQUEST_COUNT = "INVALID_REQUEST_COUNT",
  PURPOSE_AND_STATUS_NOT_UNIQUE = "PURPOSE_AND_STATUS_NOT_UNIQUE",
}
