openapi: 3.0.0
info:
  title: Tracing Operations API
  description: API for tracing operations
  version: 1.0.0
tags:
  - name: Write
    description: Operations related to writing data
  - name: Read
    description: Operations related to reading data
paths:
  /tracings/submit:
    post:
      summary: Submit tracing request
      operationId: submitTracing
      tags:
        - Write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitTracingRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitTracingResponse"
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "404":
          description: The requested resource could not be found on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem404"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/{tracingId}/recover:
    post:
      summary: Update tracing with state error by tracingId
      operationId: recoverTracing
      tags:
        - Write
      parameters:
        - name: tracingId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateOnErrorResponse"
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "404":
          description: The requested resource could not be found on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem404"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/{tracingId}/replace:
    post:
      summary: Replace tracing with complete state by tracingId
      operationId: replaceTracing
      tags:
        - Write
      parameters:
        - name: tracingId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateOnCompleteResponse"
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "404":
          description: The requested resource could not be found on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem404"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/{tracingId}/versions/{version}/state:
    post:
      summary: Update tracing state by tracingId
      operationId: updateState
      tags:
        - Write
      parameters:
        - name: tracingId
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TracingStateUpdateRequest"
      responses:
        "204":
          description: No content
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "404":
          description: The requested resource could not be found on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem404"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/{tracingId}/versions/{version}/savePurposeError:
    post:
      summary: Save purpose error
      operationId: savePurposeError
      tags:
        - Write
      parameters:
        - name: tracingId
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SavePurposeErrorRequest"
      responses:
        "204":
          description: No content
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings:
    get:
      summary: Get all tracings of a tenant
      operationId: getTracings
      tags:
        - Read
      parameters:
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 50
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTracingsByTenantId"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/deletePurposesError:
    delete:
      summary: Delete purposes error
      operationId: deletePurposesError
      tags:
        - Write
      responses:
        "204":
          description: No content
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/state/saveMissingTracing:
    post:
      summary: Save missing tracing
      operationId: saveMissingTracing
      tags:
        - Write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaveMissingTracingRequest"
      responses:
        "204":
          description: No content
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "404":
          description: The requested resource could not be found on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem404"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"

  /tracings/{tracingId}/errorDetails:
    get:
      summary: Get error detail by tracingId
      operationId: getTracingErrors
      tags:
        - Read
      parameters:
        - name: tracingId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the tracing item to retrieve error details
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 50
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetErrorDetailResponse"
        "400":
          description: The provided input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem400"
        "404":
          description: The requested resource could not be found on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem404"
        "500":
          description: A managed error has occurred during the request elaboration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem500"
components:
  schemas:
    TracingStateUpdateRequest:
      type: object
      properties:
        state: 
          $ref: "#/components/schemas/TracingState"
      required:
        - state
    TracingState:
      type: string
      enum:
      - PENDING
      - COMPLETED
      - MISSING
      - ERROR
      
    SubmitTracingRequest:
      type: object
      properties:
        date:
          type: string
          format: date
      required:
        - tenantId
        - date
    SavePurposeErrorRequest:
      type: object
      properties:
        tenantId:
          type: string
          format: uuid
        date:
          type: string
          format: date
        error:
          type: string
        rowNumber:
          type: integer
      required:
        - tracingId
        - tenantId
        - date
        - error
        - version
    SaveMissingTracingRequest:
      type: object
      properties:
        date:
          type: string
          format: date
      required:
        - date
    GetErrorDetailResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              purposeId:
                type: string
                format: uuid
              errorCode:
                type: string
              message:
                type: string
    GetTracingsByTenantId:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              tracingId:
                type: string
              date:
                type: string
                format: date
              state:
                type: string
              errorMessage:
                type: string
        totalCount:
          type: integer
    SubmitTracingResponse:
      type: object
      properties:
        tracingId:
          type: string
          format: uuid
        tenantId:
          type: string
          format: uuid
        version:
          type: number
        errors:
          type: boolean
    UpdateOnErrorResponse:
      type: object
      properties:
        tracingId:
          type: string
          format: uuid
        tenantId:
          type: string
          format: uuid
        version:
          type: number
    UpdateOnCompleteResponse:
      type: object
      properties:
        tracingId:
          type: string
          format: uuid
        tenantId:
          type: string
          format: uuid
        version:
          type: number
    Problem500:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 500
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: "^[ -~]{0,64}$"
          type: string
        correlationId:
          description: Unique identifier of the request
          example: "53af4f2d-0c87-41ef-a645-b726a821852b"
          maxLength: 64
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: "^.{0,1024}$"
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/ProblemError"
      additionalProperties: false
      required:
        - type
        - status
        - title
        - errors
    Problem400:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 400
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: Bad Request
          example: Bad Request
          maxLength: 64
          pattern: "^[ -~]{0,64}$"
          type: string
        correlationId:
          description: Unique identifier of the request
          example: "53af4f2d-0c87-41ef-a645-b726a821852b"
          maxLength: 64
          type: string
        detail:
          description: The request could not be understood by the server due to malformed syntax.
          example: The request could not be understood by the server due to malformed syntax.
          maxLength: 4096
          pattern: "^.{0,1024}$"
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/ProblemError"
      additionalProperties: false
      required:
        - type
        - status
        - title
        - errors
    Problem404:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 404
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: Not Found
          example: Not Found
          maxLength: 64
          pattern: "^[ -~]{0,64}$"
          type: string
        correlationId:
          description: Unique identifier of the request
          example: "53af4f2d-0c87-41ef-a645-b726a821852b"
          maxLength: 64
          type: string
        detail:
          description: The requested resource could not be found.
          example: The requested resource could not be found.
          maxLength: 4096
          pattern: "^.{0,1024}$"
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/ProblemError"
      additionalProperties: false
      required:
        - type
        - status
        - title
        - errors
    ProblemError:
      properties:
        code:
          description: Internal code of the error
          example: 123-4567
          minLength: 8
          maxLength: 8
          pattern: "^[0-9]{3}-[0-9]{4}$"
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 4096
          pattern: "^.{0,1024}$"
          type: string
      required:
        - code
        - detail
